export const NET_SALE_FY = "NET_SALE_FY";
export const NET_SALE_MO = "NET_SALE_MO";
export const OUT_OF_STOCK_PRODUCTS = "OUT_OF_STOCK_PRODUCTS";
export const LOW_STOCK_PRODUCTS = "LOW_STOCK_PRODUCTS";
export const USERS_REGISTERED = "USERS_REGISTERED";
export const PROCESSING_ORDERS = "PROCESSING_ORDERS";
