export const SET_HOMESCREEN = "SET_HOMESCREEN";
export const SET_CATEGORY_SCREEN = "SET_CATEGORY_SCREEN";
export const SET_LIST_SCREEN = "SET_LIST_SCREEN";
export const SET_OVERALL = "SET_OVERALL";
export const SET_PRODUCT_SCREEN = "SET_PRODUCT_SCREEN";
export const SET_REGISTER_SCREEN = "SET_REGISTER_SCREEN";
